pool: 'default'

variables:
  node.version: '20.x'
  projectRoot: '.'

jobs:
  - job: deploy
    variables:
      - group: 'FE_VARIABLES'
    steps:
      - task: NodeTool@0
        displayName: 'Use Node.js $(node.version)'
        inputs:
          versionSpec: '$(node.version)'

      - script: |
          npm install
        workingDirectory: $(projectRoot)
        displayName: "Install dependencies"
      
      - script: |
          echo "VITE_APP_MASTER_IP=$(VITE_APP_MASTER_IP)" >> .env
          echo "VITE_APP_PUBLIC_KEY=$(VITE_APP_PUBLIC_KEY)" >> .env
          echo "VITE_APP_SERVICE_ID=$(VITE_APP_SERVICE_ID)" >> .env
          echo "VITE_APP_TEMPLATE_ID=$(VITE_APP_TEMPLATE_ID)" >> .env
          echo "VITE_APP_USER_IP=$(VITE_APP_USER_IP)" >> .env
        workingDirectory: $(projectRoot)
        displayName: "Create env file"

      - script: |
          npm run build
        workingDirectory: $(projectRoot)
        displayName: "Build project"
      
      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(projectRoot)/dist'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true
      
      - task: AzureWebApp@1
        displayName: 'Deploy Azure Web App'
        inputs:
          azureSubscription: 'script-squad-service-connection'
          appType: 'webAppLinux'
          appName: "atc-2024-script-squad-fe-linux-web-app"
          package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          startUpCommand: 'pm2 serve /home/site/wwwroot --no-daemon --spa'